/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ahlblqmjsgwtawxhnixr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFobGJscW1qc2d3dGF3eGhuaXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3MjAyNTQsImV4cCI6MjA4MDI5NjI1NH0.iz8x6AGzf7AjNysCccI3qzPxQr-Q2mq-pNfcQO8CrQo"